<a href="https://colab.research.google.com/github/chumbacash/learn-python/blob/main/learn_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#This how to start python from the start, with Hello world output

print("Hello world")

Hello world


In [4]:

#variables
# they are used to store data

fruits = ["apple", "banana", "cherry"]
x, y, z = fruits
print(x)
print(y)
print(z)

apple
banana
cherry


In [5]:
x = "Python"
y = "is"
z = "awesome"
print(x, y, z)

Python is awesome


In [6]:
x = 5
y = "Amon"
print(x, y)

5 Amon


In [7]:
print(x)

5


In [8]:
x = "awesome"

def myfunc():
  print("Python is ", x)

myfunc()

Python is  awesome


In [9]:
#global variables

def myfunc():
  global x
  x = "fantastic"

myfunc()

print("Python is ", x)

Python is  fantastic


In [10]:
#check type in a string

x = "Hello world"

print(type(x))

<class 'str'>


In [11]:
#check type in a list

x = ["apple", "Banana", "cherry"]

print(type(x))

<class 'list'>


In [12]:
y = 6j

print(type(y))

<class 'complex'>


In [13]:
import random

print(random.randrange(1, 10))

2


In [14]:
#strings are arrays

a = "Hello,  World!"
print(a[1])

e


In [15]:
for x in "Bananas":
  print(x)

B
a
n
a
n
a
s


In [16]:
#string lenght

a = "Hello, World!"

print(len(a))

13


In [17]:
#check string

txt = "Everything in life is for free. How you acquire them matters"
print("free" in txt)

True


In [18]:
#Using the previous a to solve other problems
#learn slicing

print(a[2:5]) #Slicing
print(a[:5]) #Slice From the Start
print(a[2:]) #Slice To the End

#negative indexing
print(a[-5:-2])

llo
Hello
llo, World!
orl


In [19]:
# Modify Strings

#upper case
print(a.upper())

#lower case
print(a.lower())

#remove whitespace
print(a.strip())

#replece string
print(a.replace("H", "J"))

#Split string
print(a.split(","))

HELLO, WORLD!
hello, world!
Hello, World!
Jello, World!
['Hello', ' World!']


In [20]:
#String Format

cars = 2
items_number = 7899
price = 60000

my_order = "I want {} of my cars with {} of item number for {} in dollars"
print(my_order.format(cars, items_number, price))

I want 2 of my cars with 7899 of item number for 60000 in dollars


In [21]:
#Escape Characters

# examples of o escape characters are double quote inside a string

# let's try and solve this problem,

txt = 'We are the so-called \"Vikings"\ from the north' #we used a backslash

# \n - new line
# \t - tab
# \' - single quote

print(txt)

We are the so-called "Vikings"\ from the north


In [22]:
#capitalize() -	Converts the first character to upper case

#format_map()	Formats specified values in a string

#find()	Searches the string for a specified value and returns the position of where it was found

#isdigit()	Returns True if all characters in the string are digits

In [23]:
#Booleans

#Booleans represents one of the two values: True or false

print(10>9)
print(6==7)

a = 200
b = 33

if b > a:
  print("b is greater than a")

else:
  print('b is less than a')

print(bool("15"))

def myFunc():
  return True

if myFunc():
  print("YES!")

else:
  print("NO!")

True
False
b is less than a
True
YES!


In [24]:
#Operators

#Used to perform operations on variables and values.


# +	Addition        	  x + y
# -	Subtraction	        x - y
# *	Multiplication	    x * y
# /	Division           	x / y
# %	Modulus	            x % y
# **	Exponentiation	  x ** y
# //	Floor division  	x // y

print(10 + 5)

#PYTHON LOGICAL OPERATORS

# and, or and not


15


In [25]:
#Lists

# They are used to store multiple items in a variable
#List are ordered and changeable, and allow duplicate values

fruits = ["apple", "Banana", "Pineapple"]
print(fruits)
print(len(fruits))
print(type(fruits))

# access items in a list
print(fruits[2])
print(fruits[-2])

fruits[1:3] = ["watermelon", "cherry", "mangoes"]

print(fruits)

['apple', 'Banana', 'Pineapple']
3
<class 'list'>
Pineapple
Banana
['apple', 'watermelon', 'cherry', 'mangoes']


In [26]:
# append items
# to add an item to the end of the list, use the append() method:

print(fruits)

fruits = ["banana", "apple", "cherry"]
fruits.append("oranges")
print(fruits)

fruits.insert(1, "grapes")
print(fruits)

#extend() method
#used to append elements from another list to the current list, example below:

fruits = ["banana", "apple", "cherry"]
tropical = ["mango", "pineapple", "papaya"]
fruits.extend(tropical)
print(fruits)

# also extend() method does not have to append lists, you can add any iterable object
#(tuples, sets, dicts)

#Example to add elements of a tuple to list
thistuple = ("kiwi", "watermelon")
fruits.extend(thistuple)
print(fruits)


['apple', 'watermelon', 'cherry', 'mangoes']
['banana', 'apple', 'cherry', 'oranges']
['banana', 'grapes', 'apple', 'cherry', 'oranges']
['banana', 'apple', 'cherry', 'mango', 'pineapple', 'papaya']
['banana', 'apple', 'cherry', 'mango', 'pineapple', 'papaya', 'kiwi', 'watermelon']


In [27]:
fruits = ["banana", "apple", "kiwi", "banana", "cherry"]

# the remove() method removes the first occurance:

fruits.remove("banana")
print(fruits)

#remove specified index
#if yo don't specify the index, the pop() method removes the last item:

fruits = ["banana", "apple", "cherry"]
fruits.pop(1)
print(fruits)

fruits = ["apple", "Banana", "Pineapple"]
fruits.pop() #index not specified
print(fruits)

# del keyword also removes the specified index:

fruits = ["apple", "Banana", "Pineapple"]
del fruits[0]
print(fruits)

#clear the list
# the clear() method empties the list

fruits = ["apple", "Banana", "Pineapple"]
fruits.clear()
print(fruits)

['apple', 'kiwi', 'banana', 'cherry']
['banana', 'cherry']
['apple', 'Banana']
['Banana', 'Pineapple']
[]


In [28]:
#Loop through a list

fruits = ["apple", "Banana", "cherry"]
for x in fruits:
  print(x)

# You can also loop through the list items by referring totheir index number

fruits = ["apple", "Banana", "cherry"]
for i in range(len(fruits)):
  print(fruits[i])

apple
Banana
cherry
apple
Banana
cherry


In [ ]:
# Using a While Loop
fruits = ["apple", "Banana", "cherry"]
i = 0
while i < len(fruits):
  print(fruits[i])
  i+=i

#list comprehension
[print(x) for x in fruits]

In [30]:
# sort list alphanumerically

fruits = ["orange", "mango", "kiwi", "pineapple", "banana"]
fruits.sort()
print(fruits)

numbers = [20, 3, 78, 200, 60, 30]
numbers.sort()
print(numbers)

#sort decending by using reverse = True

['banana', 'kiwi', 'mango', 'orange', 'pineapple']
[3, 20, 30, 60, 78, 200]



```
append()	Adds an element at the end of the list
clear()	 Removes all the elements from the list
copy()  	Returns a copy of the list
count() 	Returns the number of elements with the specified value
extend()	Add the elements of a list (or any iterable), to the end of the current list
index() 	Returns the index of the first element with the specified value
insert()	Adds an element at the speci fied position
pop()	Removes the element at the specified position
remove()	Removes the item with the specified value
reverse()	Reverses the order of the list
sort()	Sorts the list
```




In [32]:
#copy a list
# You cannot copy a list
# simply by typing list2 = list1, because: list2 will only be
# a reference to list1, and changes made in list1 will automatically
# also be made in list2.

fruits = ["apple", "banana", "cherry"]
myfruits = fruits.copy()
print(myfruits)

['apple', 'banana', 'cherry']


In [33]:
#TUPLE
#tuples are ordered and unchangeable
#tuples are used to store multiple items in a single variable

tuple = ("apple", "banana", "cherry")
print(tuple)

tuple = ("apple", "banana", "cherry")
print(len(tuple))

#check if item exists

if "apple" in tuple:
  print("Yes, 'apple' is in fruits tuple ")

('apple', 'banana', 'cherry')
3
Yes, 'apple' is in fruits tuple 


In [34]:
x = ("apple", "banana", "cherry")

In [35]:
#convert a tuple values

tuple = ("apple", "banana", "cherry")
y = list(tuple)
y.append("orange", )
print(tuple)

('apple', 'banana', 'cherry')




```
unpacking a tuple
```



In [36]:
fruits = ("apple", "banana", "cherry")

(green, yellow, red) = fruits
print(green)
print(yellow)
print(red)

fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")

(green, *yellow, red) = fruits

print(green)
print(yellow)
print(red)

apple
banana
cherry
apple
['banana', 'cherry', 'strawberry']
raspberry


In [37]:
#Loop through the index
# using range() and len() functions to create a suitable iterable

tuple = ("apple", "banana", "cherry")

for i in range(len(fruits)):
  print(fruits[i])

# using while loop

tuple = ("apple", "banana", "cherry")

i = 0

while i < len(tuple):
  print(tuple[i])

  i = i + 1


apple
banana
cherry
strawberry
raspberry
apple
banana
cherry


In [38]:
#Join two tuples

tuple_one = ("a", "b", "c")
tuple_two = (1, 2, 3)

tuple_three = tuple_one + tuple_two

print(tuple_three)

('a', 'b', 'c', 1, 2, 3)


In [39]:
#Python sets

set = {"apple", "banana", "cherry"}

print(set)

{'banana', 'cherry', 'apple'}


In [40]:
# Access items in a set

set = {"apple", "banana", "cherry"}

for x in set:
  print(x)


#check if item is available in the set

print("banana" in set)

banana
cherry
apple
True


In [41]:
# add set in items

set = {"apple", "banana", "cherry"}

set.add("orange")

print(set)

#To add items from another set into the current set using update() method

set = {"apple", "banana", "cherry"}
fruits = {"pineapple", "mango", "papaya"}

set.update(fruits)
print(set)

# also you can use this method to update any iterable be it tuples, lists and dics

{'banana', 'orange', 'cherry', 'apple'}
{'pineapple', 'papaya', 'mango', 'cherry', 'apple', 'banana'}




```
You can also use the pop() method to remove an item, but this method will
remove a random item, so you cannot be sure what item that gets removed.
```



In [42]:
# remove item from a set
#To remove an item in a set, use the remove(), or the discard() method.

set = {"apple", "banana", "cherry"}

set.remove("banana")

print(set)

# discard() method

set = {"apple", "banana", "cherry"}

set.discard("banana")

print(set)

#If the item to remove does not exist, discard() will NOT raise an error.

#using pop() method

set = {"apple", "banana", "cherry"}

set_two = set.pop()

print(set_two)

print(set)

# Remember clear() method empties the set

set = {"apple", "banana", "cherry"}

set.clear()

print(set)

# del method will delete set completely

set = {"apple", "banana", "cherry"}

del set

print(set)

{'cherry', 'apple'}
{'cherry', 'apple'}
banana
{'cherry', 'apple'}
set()
<class 'set'>


In [43]:
# Loop in set

set = {"apple", "banana", "cherry"}

for x in fruits:
  print(x)

pineapple
mango
papaya


In [44]:
# Join set

#using union() method
set_one = {"a", "b", "c"}
set_two = {1, 2, 3}

set_three = set_one.union(set_two)

print(set_three)

#using update() method

set_one.update(set_two)

print(set_one)

{1, 2, 3, 'b', 'a', 'c'}
{1, 2, 3, 'b', 'a', 'c'}




```
Both union() and update() will exclude any duplicate items.
```





```
Python has a set of built-in methods that you can use on sets.

Method	Description
add()  	Adds an element to the set
clear() 	Removes all the elements from the set
copy()	  Returns a copy of the set
difference()	Returns a set containing the difference between two or more sets
difference_update()	Removes the items in this set that are also included in another, specified set
discard()	Remove the specified item
intersection()	Returns a set, that is the intersection of two other sets
intersection_update()	Removes the items in this set that are not present in other, specified set(s)
isdisjoint()	Returns whether two sets have a intersection or not
issubset()	Returns whether another set contains this set or not
issuperset()	Returns whether this set contains another set or not
pop()	Removes an element from the set
remove()	Removes the specified element
symmetric_difference()	Returns a set with the symmetric differences of two sets
symmetric_difference_update()	inserts the symmetric differences from this set and another
union()	Return a set containing the union of sets
update()	Update the set with the union of this set and others
```



In [45]:
#Python Dictionaries

#Dictionaries are used to store data values in key:value pairs.
#Dictionaries are written in curly brackets, and have keys and values:

dict = {
    "brand": "Ford",
    "model": "Mustang",
    "year": 1964
}

print(dict)

#Determine the dict length using len() function

print(len(dict))

#detemine the type sung type() method

print(type(dict))

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
3
<class 'dict'>




```
- Duplicates not allowed in dictionaries
- We can make dictionaries from constructors

```



In [46]:
# The dict() constructors

# dict_one = dict(name = "John", age = 36, country = "Kenya")

# print(dict_one)





```
Python Collections (Arrays)
There are four collection data types in the Python programming language:

**List** is a collection which is ordered and changeable. Allows duplicate members.
**Tuple** is a collection which is ordered and unchangeable. Allows duplicate members.
**Set** is a collection which is unordered, unchangeable*, and unindexed. No duplicate members.
**Dictionary** is a collection which is ordered** and changeable. No duplicate members.
```



In [47]:
# Access items in a dictionary

dict ={
    "brand" : "Ford",
    "model" : "Mustang",
    "Year" : 1964

}

x = dict["model"]

print(x)

y = dict.get("brand")

print(y)

# add items to original dictionary

car ={
    "brand" : "Ford",
    "model" : "Mustang",
    "Year" : 1964

}

a = car.values()

print(a)

car["color"] = "red"

print(a)

#check if key exists in a dictionary

if "model" in car:
  print("Yes, 'model' is one of the keys in the car dictionary")

# change values in dictionary
car["Year"] = 2018

print(car)

# Update dictionary
# the update() method will update the dict with the items in arguments given

car.update({"year": 2020})

print(car)



Mustang
Ford
dict_values(['Ford', 'Mustang', 1964])
dict_values(['Ford', 'Mustang', 1964, 'red'])
Yes, 'model' is one of the keys in the car dictionary
{'brand': 'Ford', 'model': 'Mustang', 'Year': 2018, 'color': 'red'}
{'brand': 'Ford', 'model': 'Mustang', 'Year': 2018, 'color': 'red', 'year': 2020}


In [48]:
#Removeitems from a dictionary

# There are a several methods
 #using pop() models it removes item with key name
car = {
    "brand" : "Ford",
    "model" : "Mustang",
    "year" : 1964
}

car.pop("model")
print(car)

#using popitem()

car = {
    "brand" : "Ford",
    "model" : "Mustang",
    "year" : 1964
}

car.popitem()
print(car)

#del keyword can also delete dict completely error will arise

car = {
    "brand" : "Ford",
    "model" : "Mustang",
    "year" : 1964
}

del car # this will cause an error because "car" no longer exists


#clear() method empties the dict

car = {
    "brand" : "Ford",
    "model" : "Mustang",
    "year" : 1964
}

car.clear()
print(car)

#loop dictionaries

car = {
    "brand" : "Ford",
    "model" : "Mustang",
    "year" : 1964
}

for a in car:
  print(a)


# copy a dict
car = {
    "brand" : "Ford",
    "model" : "Mustang",
    "year" : 1964
}

mycar = car.copy()
print(mycar)

{'brand': 'Ford', 'year': 1964}
{'brand': 'Ford', 'model': 'Mustang'}
{}
brand
model
year
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [49]:
#Nested dictionaries
#A dictionary can contain dictionaries, this is called nested dictionaries.

myfamily = {
    "child1" : {
        "name" : "Jonah",
        "year" : 1995
    },

    "child2" : {
        "name" : "Mathew",
        "year" : 1996
    },
    "child3" : {
        "name" : "Millicent",
        "year" : 1998
    },
    "child4" : {
        "name" : "Amon",
        "year" : 2000
    },
    "child5" : {
        "name" : "Titus",
        "year" : 2009
    }
}

#to access dict use this method

print(myfamily["child4"]["name"])


Amon




```
Python has a set of built-in methods that you can use on dictionaries.

Method	Description
clear()	Removes all the elements from the dictionary
copy()	Returns a copy of the dictionary
fromkeys()	Returns a dictionary with the specified keys and value
get()	Returns the value of the specified key
items()	Returns a list containing a tuple for each key value pair
keys()	Returns a list containing the dictionary's keys
pop()	Removes the element with the specified key
popitem()	Removes the last inserted key-value pair
setdefault()	Returns the value of the specified key. If the key does not exist: insert the key, with the specified value
update()	Updates the dictionary with the specified key-value pairs
values()	Returns a list of all the values in the dictionary

```



In [50]:
# if .... else in python

# Equals: a == b
# Not Equals: a != b
# Less than: a < b
# Less than or equal to: a <= b
# Greater than: a > b
# Greater than or equal to: a >= b

#if
a = 53
b = 178

if b > a:
  print("b is greater than a") # will raise an error if not indented

#Indentation - Python relies on identation

#elif

a = 33
b = 33
if b > 33:
  print("b is greater than a")

elif a == b:
  print("a and b are equal")

#else

a = 198
b = 24

if b > a:
  print("b is greater that a")

elif a == b:
  print("a and b are equal")

else:
  print("a is greater than b")

# Lets test "And" keyword

a = 198
b = 24
c = 630

if a > b and c > a:
  print("Both condions are True")

#The "or" keyword
a = 198
b = 24
c = 630

if a > b or a > c:
  print("At least one of the condions are True")

# The not keyword

a = 22
b = 240

if not a > b:
  print("a is NOT greater than b")

#Nested if

a = 41

if a > 10:
  print("above ten,")
  if a > 20:
    print("and also above 20!")

  else:
    print("but not above 20.")

#The pass statement
a = 33
b = 200

if b > a:
  pass

b is greater than a
a and b are equal
a is greater than b
Both condions are True
At least one of the condions are True
a is NOT greater than b
above ten,
and also above 20!


In [51]:
#Python while loops
# using while and for loops

#The while loop

i = 1
while i < 6:
  print(i)
  i = i + 1

#The break statement

i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i = i + 1

#continue statement


# i = 1
# while i < 6:
#   print(i)
#   if i == 3:
#     continue
#   i = i + 1

#The else statement


i = 1
while i < 6:
  print(i)
  i = i + 1

else:
  print("i is no longer less than 6")

1
2
3
4
5
1
2
3
1
2
3
4
5
i is no longer less than 6


In [52]:
# Python for loops
#A for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string).
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

# The range() function

for x in range (6):
  print(x)
else: #else in for loop
  print("Finally finished!")

#Nested Loops
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y)

apple
banana
cherry
0
1
2
3
4
5
Finally finished!
red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


In [53]:
#Python functions
# Fuctions is a block of code which runs, you can pass data or parameters

#Creating a function using "def" keyword

def my_function():
  print("Hello from a function")

my_function() #ensure you call the function at the end of the work

#Arguments they are often shorted as "args"

#information a can be passed into functions as arguments

def my_function(fname):
  print(fname, "Chepchieng")

my_function("Jonah")
my_function("Amon")
my_function("Mathew")

#Number of arguments
def my_function(fname, lname):
  print(fname, " ", lname)

my_function("AMON", "CHEPCHIENG")

Hello from a function
Jonah Chepchieng
Amon Chepchieng
Mathew Chepchieng
AMON   CHEPCHIENG


In [54]:
# Arbitrary arguments, *args
# This is used when the number of arguments to be passed is not known. Function will receive tuple args

def my_family(*kids):
  print("The youngest child is" , kids[2]) #the 2 is used to indicate the position

my_family("Amon", "Millicent", "Titus")

#Keyword arguments often shorted as kwargs

def my_family(child3, child2, child1):
  print("The youngest child is", child3)

my_family(child1 = "Millicent", child2 = "Amon", child3 = "Titus")

# Arbitrary keyword Arguments, **kwargs
# We use it if we don't know the number of args to be passed, function will receive dict of args

def my_name(**kid):
  print("His last name is", kid["lname"])

my_name(fname = "Titus", lname = "Chepchieng")

The youngest child is Titus
The youngest child is Titus
His last name is Chepchieng


In [55]:
#Default parameter value
#If we call the function without an argument, it uses default value

def my_function(country = "Norway"):
  print("I am from", country)

my_function("Sweden")
my_function("India")
my_function()
my_function("Kenya")

#Passing a list as an argument

def my_function(food):
  for x in food:
    print(x)

fruits = ["apple", "banana", "cherry"]

my_function(fruits)

#Positional-Only Arguments

def my_function(x,/):
  print(x)

my_function(3)

I am from Sweden
I am from India
I am from Norway
I am from Kenya
apple
banana
cherry
3


In [56]:
#Python Lambda
#This is a small anonymous function

x = lambda a : a + 10
print(x(5))

#Multiply argument a with argument b and return the result
x = lambda a, b : a * b
print(x(5,6))

15
30


In [57]:
#Colab AI

square = lambda x: x ** 2
print(square(5))  # Output: 25

25


In [58]:
# Python Arrays - For this lists are always reffered

#create an array  - arrays are used to store multiple values in one single var:

cars = ["Ford", "Volvo", "BMW"]

cars.append("Honda")

print(cars)

['Ford', 'Volvo', 'BMW', 'Honda']


In [62]:
'''Python classes/Objects

Python classes an object oriented programming language, class is a like an object constructor
or a "blueprint" for creating objects

Create a class, use the keyword class:'''

# class MyClass:
#   x = 5
#   p1 = MyClass()
# #  print(p1.x)




'Python classes/Objects\n\nPython classes an object oriented programming language, class is a like an object constructor\nor a "blueprint" for creating objects\n\nCreate a class, use the keyword class:'

In [63]:
#The __init__() function

class Person:

  def __init__(self, name, age):
    self.name = name
    self.age = age
    pass

p1 = Person("John", 36)

print(p1.name)
print(p1.age)

#The __str__() Function

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age


  def __str__(self):
    return f"{self.name}({self.age})"

p1 = Person("AMON", 36)

print(p1)


John
36
AMON(36)


In [64]:
#Inheritance

class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname


  def printname(self):
    print(self.firstname, self.lastname)


x = Person("Amon", "Chepchieng")
x.printname()

Amon Chepchieng


In [65]:
#Print and return

'''print is just a function while return is just a keyword'''

def func1(a,b):
  c = a + b
  print(c)

func1(3,4)

def func1(a,b):
  c = a + b
  return c

output = func1(3,4)
print(output)

7
7


In [66]:
#Python iterators
'''An iterator is an object that contains a countable number of values'''

tuple = ("apple", "banana", "cherry")

myit = iter(tuple)

print(next(myit))
print(next(myit))
print(next(myit))

#Srings are iterable also:

mystr = "banana"
myit = iter(mystr)

print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))

apple
banana
cherry
b
a
n
a
n
a


In [67]:
#Create an Iterator
'''To create an object/class as an iterator you have to
implement the methods __iter__() and __next__() to your object.
all classes have a function called __init__(),
which allows you to do some initializing when the object
 is being created.'''

class MyNumbers:
  def __iter__(self):
    self.a = 1
    return self

  def __next__(self):
    x = self.a
    self.a += 1
    return x

myclass = MyNumbers()
myiter = iter(myclass)

print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))

1
2
3
4
5


In [68]:
#Polymorphism
'''The word "polymorphism" means "many forms",
and in programming it refers to
methods/functions/operators with the same name
that can be executed on many objects or classes.'''

#string
x = "Hello World!"

print(len(x))

#Tuple
mytuple = ("apple", "banana", "cherry")

print(len(mytuple))

#Dictionary

dict = {
    "brand" :"Ford",
    "model" :"Mustang",
    "year" : 1964
}

print(len(dict))

12
3
3


In [69]:
#Class polymorphism

class Car:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Drive!")

class Boat:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Sail!")

class Plane:
  def __init__(self, brand, model):
    self.brand = brand
    self.model = model

  def move(self):
    print("Fly!")

car1 = Car("Ford", "Mustang")
boat1 = Boat("Ibiza", "Touring 20")
plane1 = Plane("Boeing", "747")

for x in (car1, boat1, plane1):
  x.move()

Drive!
Sail!
Fly!


In [70]:
#Python scope
#A variable is only available from inside the region it is created.

#Local scope

def myfunc():
  x = 300
  print(x)

myfunc()

#Local variable ---

def myfunc():
  x = 300
  def myinnerfunc():
    print(x)
    myinnerfunc()

myfunc()

#Global Scope -> It's available within any scope, global and local

x = 250

def myfunc():
  print(x)

myfunc()

print(x)

#Global Keyword
def myfunc():
  global x
  x = 424

myfunc()

print(x)

300
250
250
424


In [71]:
#Python Modules --> a file containig set of functions you want in your app

#Create a Module ---> have a file extension .py: it can  be used to import

import platform

x = platform.system()
print(x)

a = dir(platform)
print(a)

Linux
['_Processor', '_WIN32_CLIENT_RELEASES', '_WIN32_SERVER_RELEASES', '__builtins__', '__cached__', '__copyright__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '_comparable_version', '_component_re', '_default_architecture', '_follow_symlinks', '_get_machine_win32', '_ironpython26_sys_version_parser', '_ironpython_sys_version_parser', '_java_getprop', '_libc_search', '_mac_ver_xml', '_node', '_norm_version', '_os_release_cache', '_os_release_candidates', '_os_release_line', '_os_release_unescape', '_parse_os_release', '_platform', '_platform_cache', '_pypy_sys_version_parser', '_sys_version', '_sys_version_cache', '_sys_version_parser', '_syscmd_file', '_syscmd_ver', '_uname_cache', '_unknown_as_blank', '_ver_output', '_ver_stages', 'architecture', 'collections', 'freedesktop_os_release', 'functools', 'itertools', 'java_ver', 'libc_ver', 'mac_ver', 'machine', 'node', 'os', 'platform', 'processor', 'python_branch', 'python_build', 'pyth

In [72]:
#Python Datetime
#Date in python is not a date type of its own, but we import a module

import datetime

a = datetime.datetime.now()
print(a)

2024-02-11 07:45:14.042704


In [73]:
#Python math module

x = min(2, 7, 27)
y = max(2, 7, 27)

print(x)
print(y)

import math

a = math.sqrt(64)
print(a)

b = math.pi
print(b)

2
27
8.0
3.141592653589793


In [74]:
#Python JSON
'''JSON is a syntax for storing and exchanging data.
JSON is text, written with JavaScript object notation.'''

#Convert from JSON to Python ---> json.loads() method
import json

c = '{ "name": "John", "age":30, "city": "New York" }'

y = json.loads(c)

print(y["age"])



30


In [75]:
#Python RegEx
'''A RegEx, or Regular Expression,
is a sequence of characters that forms a search pattern.
RegEx can be used to check if a string contains the specified
search pattern.'''

import re

txt = "The rain in Spain"
x = re.search("^The.*Spain$", txt)



In [76]:
#Python PIP --> Python packages, or modules

#Package --> contains all the files you neeed in a module

#Check pip module (pip --version)



```
The try block lets you test a block of code for errors.

The except block lets you handle the error.

The else block lets you execute code when there is no error.

The finally block lets you execute code, regardless of the result of the try- and except blocks.
```



In [77]:
#Try ...Except

#Exception Handling

try:
  print(mey) #try will generate exception since mey is not defined
except:
  print("An exception occurred")

An exception occurred


In [78]:
#Many Exceptions

try:
  print(mey)
except NameError:
  print("Variable mey is not defined")
except:
  print("Something else went wrong")

#Else
'''You can use the else keyword
to define a block of code to be executed if no errors were raised:'''

try:
  print("Hello")
except:
  print("Something went wrong")
else:
  print("Nothing went wrong")

#Finally

try:
  print(mey)
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")

Variable mey is not defined
Hello
Nothing went wrong
Something went wrong
The 'try except' is finished


**Example**


```
Raise an error and stop the program if x is lower than 0:
```



In [79]:
# r = -1

# if r < 0:
#   raise Exception("Sorry, no numbers below zero")

In [80]:
#Python User Input

username = input("Enter the username: ")
print("Username is:", username)

Enter the username: Chumbacash
Username is: Chumbacash


In [81]:
#MATPLOTLIB

import matplotlib #importing the matplotlib module

print(matplotlib.__version__) #checking the version of matplotlib

3.7.1


In [82]:
#Matplotlib Pyplot

'''Most of the matplotlib utilities lies under the "pyplot" submodule,
and are usually imported under the plt'''

import matplotlib.pyplot as plt
import numpy as np

**NumPy Tutorial**


*   Numpy is a python library
*   Numpy is used for working with arrays.
*   Numpy is short of "Numerical Python".







```
NumPy aims to provide an
array object that is up to 50x
faster than traditional Python lists
```



In [83]:
#Numpy introduction

import numpy # also you can import as np then use np down

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

import numpy as np

print(np.__version__)

[1 2 3 4 5]
1.23.5


In [84]:
#Creating array using Numpy

#The array object in Numpy is called "ndarray"

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

#Dimensions in Arrays
''' A dimension in arrays is one level of array depth (nested arrays)
nested array are arrays that have arrays as their elements'''

#0-D arrays
'''0 -D arrays, or scalars, are the elements in an array.
each value in an array is a 0-D array. '''


#Example --> Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)

#1-D arrays
''' An array that has 0-d arrays as its elements is called uni-dimensional
or 1-D'''

#Example --> Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

#2-D arrays
'''An array that has 1-D arrays as its elements is called a 2-D array.'''

#Example -->Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

#3-D arrays
'''An array that has 2-D arrays (matrices) as its elements is called 3-D array.'''

#Example --> Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]])

print(arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [85]:
#Check Number of dimensions
''' Numpy arrays provide the ndim attribute that returns an interger that
tells us how many dimensions the array have'''

#Example --> Check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [86]:
#Higher Dimensional Arrays
''' An array can have any number of dimensions'''

' An array can have any number of dimensions'

**Example**


```
Create an array with 5 dimensions and verify
that it has 5 dimensions:
```



In [87]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin = 5)

print(arr)
print("Number of dimensions: ", arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions:  5


In [88]:
# Access Array Elements
'''Array indexing is the same as accessing an array element'''

#Example --> Get the first element fromfrom the following array:

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

print(arr[2] + arr[3])

#Access 2-D Arrays

#Example --> Access the element on the row, second column:

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("2nd element on 1st row: ", arr[0, 1])

print("2nd row, 5th element: ", arr[1, 4])

#Access 3-D Arrays

#Example --> Access the third element of the second array of the first array
import numpy as np

arr = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

1
7
2nd element on 1st row:  2
2nd row, 5th element:  10


In [89]:
#Numpy Array Slicing

'''slicing arrays'''

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

#step

print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[2 4]
[1 3 5 7]


In [90]:
#Numpy Data Types

#Data Types in Python
'''These are strings, interger, float, boolean, complex'''

#ints

import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

#strings
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

#Example --> Create an array with data type 4 bytes interger:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype = 'i4')

print(arr)
print(arr.dtype)



int64
<U6
[1 2 3 4]
int32


In [93]:
#Array Shape
'''The shape of an array is the number of elements in each dimension.'''

#Example --> Print the shape of a 2-D array
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

#Example
'''Create an array with 5 dimensions using ndmin using a vector with
values 1,2,3,4 and verify that last dimension has value 4:'''

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array: ', arr.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array:  (1, 1, 1, 1, 4)


In [96]:
#Array Reshaping --> Changing the shape of an array

#Reshape from 1-D to 2-D
'''Convert the following 1-D array with 12 elements into a 2-D array.
The outermost dimension will have 4 arrays, each with 3 elements:'''

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

#Reshape from 1-D to 3-D

#Example
'''Convert the following 1-D array with 12 elements into a 3-D array.The
outermost dimension will have 2 arrays that contains 3 arrays,
each with 2 elements:'''

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [101]:
#Numpy arrays iteration --> means going through elements one by one

#Iterate on the elements of the following 1-D array:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

#Iterate on the elements of the following 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

for x in arr: #Iterate on the each scalar element of the 2-D array:
  for y in x:
    print(y)

#Iterating 3-D Arrays

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

for x in arr:
  for y in x:
    for z in y: #Iterate on each scaar element of the 3-D arrays:
      print(z)

1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


In [116]:
#Joining array

#Joining using concantate() function

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

#Join two 2-D arrays along row (axis = 1):

arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1 , arr2), axis = 1)

print(arr)

#Also we can join arrays usinb stack() method the only diff is that
# stacking is done along new axis.

#stack()
# Example

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis = 1)
print(arr)

#hstack() --> NumPy provides a helper function: hstack() to stack along rows.

arr = np.hstack((arr1, arr2))
print(arr)

#vstack() -->:vstack()  to stack along columns.

arr = np.vstack((arr1, arr2))
print(arr)

#dsctack() --> dstack() to stack along height, which is the same as depth.

arr = np.dstack((arr1, arr2))

print(arr)


[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [121]:
#Numpy Splitting Array --> reverse operation of joining

#Using array_split()

#Example--> split in 3 parts

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

# Split into 4 parts: #Using previous array list

newarr = np.array_split(arr, 4)

print(newarr)

#Split into Arrays

#Using previous array list

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

#Splitting 2-D arrays

arr = ([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[1 2]
[3 4]
[5 6]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [133]:
#Searching Arrays --> using where() method

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

#Finding indexes where the values are even

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

#Finding indexes where the values are odd

x = np.where(arr%2 == 1)

print(x)

#Search Sorted
'''There is a method called searchsorted() which performs a binary search
in the array, and returns the index whre the specified value would
be insrted to maintain the search order'''

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

#Search from the right side

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side = 'right')

print(x)

#Find the indexes where the values 2, 4, and 6 should be inserted:

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

(array([3, 5, 6]),)
(array([1, 3, 5, 7]),)
(array([0, 2, 4, 6]),)
1
2
[1 2 3]


In [138]:
#Numpy Sorting

#Sorting arrays: Using ordered sequence eg numerical or alphabetical
#Using function called sort()

#Sort the array:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

#Sort the array alphabetically:

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

#Sort a Boolean array

arr= np.array([True, False, True])

print(np.sort(arr))

#Sort a 2-D array

arr = np.array([[3, 2,4], [5, 0, 1]])

print(np.sort(arr))

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]
[[2 3 4]
 [0 1 5]]


In [141]:
#Numpy Filter arrays
''' Getting some elements out of an existing array and creating a new array
out of them is called filtering.Youfilter an array using boolean index list'''

#Create an array from the elements on index 0 and 2:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

# Create a filter array that will return only even elements from the original array:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[41 43]
[False  True False  True False  True False  True]
[2 4 6 8]


In [ ]:
#Random numbers in Numpy

'''Random number does NOT mean a different number every time. Random means
something that can not be predicted logically.'''



Pseudo Random and True Random.
Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless it is related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

# In this tutorial we will be using pseudo random numbers.

In [152]:
#Generate Random numbers

import numpy

from numpy import random

x = random.randint(100) #Intergers

print(x)

x = random.rand() #Generate a random float btwn 0 and 1

print(x)

#Generate Random Array:1-D array containing 5 random integers from 0 to 100

x = random.randint(100, size =(5))

print(x)

#Generate 2-D array containing 5random integers from 0 to 100

x = random.randint(100, size = (3, 5))

print(x)
#print(np.sort(x)) #Sorting the array generated

#Floats

#Example --> Generate a 1-D array containing 5 random floats

x = random.rand(5)

print(x)

#Example --> Gnerate a 2-D array with 3 rows, each row containing 5 rand No

x = random.rand(3, 5)

print(x)

67
0.3607091412054654
[51 55 23 60 82]
[[48  9 24 91 38]
 [59 17 91 19 70]
 [65 96 30 16 74]]
[0.49943744 0.46351832 0.54888988 0.78170351 0.93841335]
[[0.87296657 0.45589378 0.02927517 0.83679267 0.1680795 ]
 [0.23847599 0.12680925 0.46857281 0.49272795 0.94339652]
 [0.02516812 0.24442225 0.44050692 0.90963468 0.10698575]]


In [154]:
#Generate random number from array
#The choice() method allows you to generate random values based on an array of values

import numpy

from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

x= random.choice([3, 5, 7, 9], size = (3, 5)) #Generate 2-D array

print(x)

9
[[5 3 3 3 5]
 [7 3 9 5 7]
 [7 7 3 5 5]]


Random Data Distribution --> is a list of all possible values, and how often each value occurs.



A random distribution is a set of random numbers that follow a certain probability density function.



In [160]:
#Example
'''Generate a 1-D array containing 100 values,
where each value has to be 3, 5, 7 or 9.

The probability for the value to be 3 is set to be 0.1

The probability for the value to be 5 is set to be 0.3

The probability for the value to be 7 is set to be 0.6

The probability for the value to be 9 is set to be 0 '''

from numpy import random

x = random.choice([3, 5, 7, 9], p = [0.1, 0.3, 0.6, 0.0], size = (100))

print(x)

x = random.choice([3, 5, 7, 9], p = [0.1, 0.3, 0.6, 0.0], size = (3, 5))

print(x)

[7 7 5 7 7 5 7 7 7 7 7 7 7 5 7 5 7 5 7 7 7 7 7 5 7 7 7 7 7 5 3 5 5 7 7 5 5
 7 5 7 5 5 5 5 5 7 7 5 5 5 7 7 7 7 7 5 5 5 7 7 7 7 7 7 3 7 7 7 7 7 7 5 7 5
 5 7 5 7 5 5 7 7 3 7 3 5 3 5 7 5 7 7 7 7 7 3 7 7 7 7]
[[7 5 7 7 3]
 [3 7 7 7 7]
 [7 7 7 7 5]]
